version: '3.8'

services:
  # PostgreSQL Database for development
  postgres-dev:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: aivideomaker_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    networks:
      - aivideomaker-dev-network

  # Redis for development
  redis-dev:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    ports:
      - "6380:6379"  # Different port to avoid conflicts
    networks:
      - aivideomaker-dev-network

  # Development environment (without building, using local code)
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      ENVIRONMENT: development
      HOST: 0.0.0.0
      PORT: 8000
      DEBUG: true
      DATABASE_URL: postgresql://postgres:postgres123@postgres-dev:5432/aivideomaker_dev
      REDIS_HOST: redis-dev
      REDIS_PORT: 6379
      SECRET_KEY: dev-secret-key-not-for-production
      JWT_SECRET_KEY: dev-jwt-secret-key-not-for-production
      CORS_ORIGINS: http://localhost:3000,http://localhost:8000,http://localhost:3001
      BASE_URL: http://localhost:8000
      FRONTEND_URL: http://localhost:8000
      # Add your development API keys here
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    volumes:
      # Mount source code for hot reloading
      - .:/app
      - dev_uploads:/app/app/static/uploads
      - dev_outputs:/app/app/static/outputs
      - dev_temp:/app/app/static/temp
      # Don't mount __pycache__ and other Python cache directories
      - /app/__pycache__
      - /app/.pytest_cache
    ports:
      - "8001:8000"  # Different port for development
    depends_on:
      - postgres-dev
      - redis-dev
    networks:
      - aivideomaker-dev-network
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    stdin_open: true
    tty: true

volumes:
  postgres_dev_data:
  redis_dev_data:
  dev_uploads:
  dev_outputs:
  dev_temp:

networks:
  aivideomaker-dev-network:
    driver: bridge